export const DEMO_FIELDS = [
  {
    id: "post_office",
    label: "Post Office",
    type: "text",
    value: "Delhi GPO",
    required: true,
    page: 1,
    bbox: { top: 0.13, left: 0.08, width: 0.25, height: 0.03 },
  },
  {
    id: "date",
    label: "Date",
    type: "date",
    value: "2026-05-06",
    required: true,
    page: 1,
    bbox: { top: 0.13, left: 0.75, width: 0.2, height: 0.03 },
  },
  {
    id: "cif_id",
    label: "CIF ID",
    type: "text",
    value: "CIF00128374",
    required: true,
    page: 1,
    bbox: { top: 0.16, left: 0.08, width: 0.3, height: 0.03 },
  },
  {
    id: "primary_account_id",
    label: "Primary Account ID",
    type: "text",
    value: "SB/2024/00183",
    required: true,
    page: 1,
    bbox: { top: 0.16, left: 0.5, width: 0.3, height: 0.03 },
  },
  {
    id: "first_name",
    label: "First Name",
    type: "text",
    value: "RJKulthneep",
    required: true,
    page: 1,
    bbox: { top: 0.27, left: 0.08, width: 0.55, height: 0.03 },
  },
  {
    id: "middle_name",
    label: "Middle Name",
    type: "text",
    value: "",
    required: false,
    page: 1,
    bbox: { top: 0.3, left: 0.08, width: 0.55, height: 0.03 },
  },
  {
    id: "last_name",
    label: "Last Name",
    type: "text",
    value: "Sharma",
    required: true,
    page: 1,
    bbox: { top: 0.33, left: 0.08, width: 0.55, height: 0.03 },
  },
  {
    id: "atm_card_for",
    label: "ATM Card For",
    type: "text",
    value: "Self",
    required: false,
    page: 1,
    bbox: { top: 0.39, left: 0.08, width: 0.12, height: 0.03 },
  },
  {
    id: "mobile_number",
    label: "Mobile Number",
    type: "number",
    value: "6378951260",
    required: true,
    page: 1,
    bbox: { top: 0.43, left: 0.15, width: 0.22, height: 0.03 },
  },
  {
    id: "pan_number",
    label: "PAN Number",
    type: "text",
    value: "BFKPR1234J",
    required: true,
    page: 1,
    bbox: { top: 0.43, left: 0.55, width: 0.22, height: 0.03 },
  },
  {
    id: "email_id",
    label: "Email ID",
    type: "email",
    value: "rjk@example.com",
    required: false,
    page: 1,
    bbox: { top: 0.46, left: 0.15, width: 0.35, height: 0.03 },
  },
  {
    id: "date_of_birth",
    label: "Date of Birth",
    type: "date",
    value: "1990-03-15",
    required: true,
    page: 1,
    bbox: { top: 0.49, left: 0.15, width: 0.18, height: 0.03 },
  },
  {
    id: "mothers_maiden_name",
    label: "Mother's Maiden Name",
    type: "text",
    value: "Parvati Devi",
    required: false,
    page: 1,
    bbox: { top: 0.49, left: 0.55, width: 0.2, height: 0.03 },
  },
  {
    id: "internet_banking",
    label: "Internet Banking",
    type: "checkbox",
    value: true,
    required: false,
    page: 1,
    bbox: { top: 0.65, left: 0.82, width: 0.1, height: 0.03 },
  },
  {
    id: "sms_banking",
    label: "SMS Banking",
    type: "checkbox",
    value: true,
    required: false,
    page: 1,
    bbox: { top: 0.68, left: 0.82, width: 0.1, height: 0.03 },
  },
];
