export const DEMO_FIELDS = [
  {
    id: "account_holder_name",
    label: "Account Holder Name",
    type: "text",
    value: "",
    required: true,
    page: 1,
    bbox: { top: 0.15, left: 0.1, width: 0.3, height: 0.05 },
  },
  {
    id: "account_number",
    label: "Account Number",
    type: "number",
    value: "",
    required: true,
    page: 1,
    bbox: { top: 0.25, left: 0.1, width: 0.3, height: 0.05 },
  },
  {
    id: "dob",
    label: "Date of Birth",
    type: "date",
    value: "",
    required: true,
    page: 1,
    bbox: { top: 0.35, left: 0.1, width: 0.3, height: 0.05 },
  },
  {
    id: "account_type",
    label: "Account Type",
    type: "select",
    value: "",
    required: true,
    options: ["Savings", "Current", "Fixed Deposit", "NRI"],
    page: 1,
    bbox: { top: 0.45, left: 0.1, width: 0.3, height: 0.05 },
  },
  {
    id: "pan_number",
    label: "PAN Number",
    type: "text",
    value: "",
    required: true,
    page: 1,
    bbox: { top: 0.55, left: 0.1, width: 0.3, height: 0.05 },
  },
  {
    id: "mobile",
    label: "Mobile Number",
    type: "number",
    value: "",
    required: true,
    page: 1,
    bbox: { top: 0.65, left: 0.1, width: 0.3, height: 0.05 },
  },
  {
    id: "email",
    label: "Email Address",
    type: "text",
    value: "",
    required: true,
    page: 1,
    bbox: { top: 0.15, left: 0.5, width: 0.3, height: 0.05 },
  },
  {
    id: "nominee_name",
    label: "Nominee Name",
    type: "text",
    value: "",
    required: false,
    page: 1,
    bbox: { top: 0.25, left: 0.5, width: 0.3, height: 0.05 },
  },
  {
    id: "internet_banking",
    label: "Internet Banking",
    type: "checkbox",
    value: false,
    required: false,
    page: 1,
    bbox: { top: 0.35, left: 0.5, width: 0.15, height: 0.05 },
  },
  {
    id: "sms_alerts",
    label: "SMS Alerts",
    type: "checkbox",
    value: false,
    required: false,
    page: 1,
    bbox: { top: 0.45, left: 0.5, width: 0.15, height: 0.05 },
  },
];
